/*****************************************************
*     008_Service_Account_Setup.sql
*
*     2025-01-15     CBECK     Initial Setup
*****************************************************/

/*************************************
* CREATE TWO SERVICE ACCOUNTS
* --ONE FOR READ/ONE FOR WRITE
* --GRANT APPROPRIATE DOMO ROLES TO ACCOUNTS
**************************************/


/*DOMO READ SERVICE ACCOUNT */
USE ROLE SECURITYADMIN;
CREATE USER DOMO_READER_SVC_01
    DISPLAY_NAME = 'DOMO READER SERVICE ACCOUNT'
	TYPE=SERVICE
    DEFAULT_ROLE = 'DOMO_READER_ROLE'
    DEFAULT_WAREHOUSE = 'DOMO_READ_XS_WH'
	RSA_PUBLIC_KEY='MIIB....'
	NETWORK_POLICY = DOMO_INBOUND_NETWORK_POLICY;
GRANT ROLE DOMO_READER_ROLE TO USER DOMO_READER_SVC_01;

/*DOMO READ WRITE ACCOUNT */
USE ROLE SECURITYADMIN;
CREATE USER DOMO_WRITER_SVC_01
    DISPLAY_NAME = 'DOMO WRITER SERVICE ACCOUNT'
	TYPE=SERVICE
    DEFAULT_ROLE = 'DOMO_WRITER_ROLE'
    DEFAULT_WAREHOUSE = 'DOMO_WRITE_XS_WH'
	RSA_PUBLIC_KEY='MIIB....'
	NETWORK_POLICY = DOMO_INBOUND_NETWORK_POLICY;
GRANT ROLE DOMO_WRITER_ROLE TO USER DOMO_WRITER_SVC_01;
